spring:
  profiles:
    active: "Local"
  main:
    banner-mode: "off"    

---

spring:
    profiles: Local
spring.datasource.driver-class-name: oracle.jdbc.driver.OracleDriver
spring.datasource.url: jdbc:oracle:thin:@ech-10-168-142-171.mastercard.int:1527:devcloud
spring.datasource.username: devadmin
spring.datasource.password: UBF12345
spring.datasource.tomcat.max-wait: 10000
spring.datasource.tomcat.max-active: 1000
spring.datasource.tomcat.test-on-borrow: true
server.port: 9097
